"""
Generate static redirect pages + nginx + Caddy snippets from databags/redirects.yaml.

For each entry in databags/redirects.yaml the script produces:

  1. content/<from-path>/contents.lr with _model: redirect, target: <to>.
     Lektor renders this as a static HTML page that performs a meta-refresh
     + JS replace + emits a canonical link pointing to the new URL. Works
     the instant the build deploys.

  2. site-config/redirects.nginx.conf  (run after `make build` so the file
     also gets copied into site/ as a deploy artefact). Contains real
     server-side 301 / 302 statements for the hoster to paste in.

  3. site-config/Caddyfile.redirects   Same intent, Caddy syntax. Caddy is
     used by some staging environments.

The script is idempotent: it removes any orphan content/<...>/contents.lr
that points to a path no longer in the YAML (so deleting a redirect cleans
the static page on the next run).
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
CONTENT = REPO / "content"
YAML_PATH = REPO / "databags" / "redirects.yaml"
NGINX_OUT = REPO / "site-config" / "redirects.nginx.conf"
CADDY_OUT = REPO / "site-config" / "Caddyfile.redirects"

# Marker line written into generated content/<...>/contents.lr files so we
# can distinguish them from hand-edited pages and prune safely.
MARKER = "# managed-by-generate_redirects.py — do not edit"


def normalise_path(p: str) -> str:
    """Strip leading/trailing whitespace, force leading and trailing slash."""
    p = p.strip()
    if not p.startswith("/"):
        p = "/" + p
    if not p.endswith("/") and "." not in p.rsplit("/", 1)[-1]:
        p = p + "/"
    return p


def load_redirects() -> list[dict]:
    data = yaml.safe_load(YAML_PATH.read_text(encoding="utf-8")) or {}
    entries = data.get("redirects") or []
    out: list[dict] = []
    for raw in entries:
        if not isinstance(raw, dict):
            continue
        fr = normalise_path(raw["from"])
        to = raw["to"].strip()
        if "://" not in to and not to.startswith("/"):
            to = "/" + to
        out.append({
            "from": fr,
            "to": to,
            "status": int(raw.get("status", 301)),
            "note": raw.get("note", "").strip(),
        })
    return out


def write_html_redirect(entry: dict) -> Path:
    """Write content/<from>/contents.lr that renders an HTML redirect."""
    rel = entry["from"].strip("/")
    target_dir = CONTENT / rel
    target_dir.mkdir(parents=True, exist_ok=True)
    lr = target_dir / "contents.lr"
    body = (
        "_model: redirect\n"
        f"---\n"
        f"target: {entry['to']}\n"
        f"---\n"
        f"status: {entry['status']}\n"
        f"---\n"
        f"note: {entry['note']}\n"
        f"---\n"
        f"_marker: {MARKER}\n"
    )
    lr.write_text(body, encoding="utf-8")
    return lr


def prune_orphan_redirects(active: set[str]) -> int:
    """Remove generated redirect content folders no longer in the YAML."""
    removed = 0
    for lr in CONTENT.rglob("contents.lr"):
        try:
            text = lr.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if MARKER not in text:
            continue
        url_path = "/" + str(lr.parent.relative_to(CONTENT)) + "/"
        if url_path not in active:
            # Delete the entire folder (it contains only our generated file).
            shutil.rmtree(lr.parent, ignore_errors=True)
            removed += 1
    return removed


def write_nginx(entries: list[dict]) -> None:
    NGINX_OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by utils/generate_redirects.py — DO NOT EDIT.",
        "# Source: databags/redirects.yaml.",
        "# Paste this inside the relevant nginx `server { ... }` block.",
        "",
    ]
    for e in entries:
        if e["note"]:
            lines.append(f"# {e['note']}")
        # Use exact-match `=` location for safety.
        lines.append(
            f"location = {e['from']} {{ return {e['status']} {e['to']}; }}"
        )
    NGINX_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_caddyfile(entries: list[dict]) -> None:
    CADDY_OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by utils/generate_redirects.py — DO NOT EDIT.",
        "# Source: databags/redirects.yaml.",
        "# Drop into the relevant Caddyfile site block.",
        "",
    ]
    for e in entries:
        if e["note"]:
            lines.append(f"# {e['note']}")
        lines.append(f"redir {e['from']} {e['to']} {e['status']}")
    CADDY_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    entries = load_redirects()
    if not entries:
        print("No redirects defined in databags/redirects.yaml.")
        # Still prune orphans + emit empty config files.
        if not args.dry_run:
            prune_orphan_redirects(set())
            write_nginx([])
            write_caddyfile([])
        return 0

    active = {e["from"] for e in entries}
    print(f"loaded {len(entries)} redirect{'s' if len(entries) != 1 else ''}.")
    if args.dry_run:
        for e in entries:
            print(f"  {e['status']} {e['from']:<40} → {e['to']}")
        return 0

    for e in entries:
        write_html_redirect(e)
    removed = prune_orphan_redirects(active)
    write_nginx(entries)
    write_caddyfile(entries)

    print(f"  wrote {len(entries)} HTML redirect pages under content/")
    print(f"  pruned {removed} orphan redirect pages")
    print(f"  wrote {NGINX_OUT}")
    print(f"  wrote {CADDY_OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
