from pathlib import Path

root = Path("/Users/hendorf/Downloads/Output")
files = [
    "PyConDE PyData 2025 Sponsoren Thanks 06.png",
    "PyConDE PyData 2025 Sponsoren Thanks 01.png",
    "PyConDE PyData 2025 Sponsoren Thanks 02.png",
    "PyConDE PyData 2025 Sponsoren Thanks 03.png",
    "PyConDE PyData 2025 Sponsoren Thanks 04.png",
    "PyConDE PyData 2025 Sponsoren Thanks 05.png",
    "PyConDE PyData 2025 Sponsoren Thanks 07.png",
    "PyConDE PyData 2025 Sponsoren Thanks 08.png",
    "PyConDE PyData 2025 Sponsoren Thanks 09.png",
    "PyConDE PyData 2025 Sponsoren Thanks 10.png",
    "PyConDE PyData 2025 Sponsoren Thanks 11.png",
    "PyConDE PyData 2025 Sponsoren Thanks 12.png",
    "PyConDE PyData 2025 Sponsoren Thanks 13.png",
    "PyConDE PyData 2025 Sponsoren Thanks 14.png",
    "PyConDE PyData 2025 Sponsoren Thanks 15.png",
    "PyConDE PyData 2025 Sponsoren Thanks 16.png",
    "PyConDE PyData 2025 Sponsoren Thanks 17.png",
    "PyConDE PyData 2025 Sponsoren Thanks 18.png",
    "PyConDE PyData 2025 Sponsoren Thanks 19.png",
    "PyConDE PyData 2025 Sponsoren Thanks 20.png",
    "PyConDE PyData 2025 Sponsoren Thanks 21.png",
    "PyConDE PyData 2025 Sponsoren Thanks 22.png",
    "PyConDE PyData 2025 Sponsoren Thanks 23.png",
    "PyConDE PyData 2025 Sponsoren Thanks 24.png",
    "PyConDE PyData 2025 Sponsoren Thanks 25.png",
    "PyConDE PyData 2025 Sponsoren Thanks 26.png",
    "PyConDE PyData 2025 Sponsoren Thanks 27.png",
    "PyConDE PyData 2025 Sponsoren Thanks 28.png",
    "PyConDE PyData 2025 Sponsoren Thanks 29.png",
    "PyConDE PyData 2025 Sponsoren Thanks 30.png",
    "PyConDE PyData 2025 Sponsoren Thanks 31.png",
    "PyConDE PyData 2025 Sponsoren Thanks 32.png",
    "PyConDE PyData 2025 Sponsoren Thanks 33.png",
    "PyConDE PyData 2025 Sponsoren Thanks 34.png",
    "PyConDE PyData 2025 Sponsoren Thanks 35.png",
    "PyConDE PyData 2025 Sponsoren Thanks 36.png",
    "PyConDE PyData 2025 Sponsoren Thanks 37.png",
    "PyConDE PyData 2025 Sponsoren Thanks 38.png",
    "PyConDE PyData 2025 Sponsoren Thanks 39.png",
    "PyConDE PyData 2025 Sponsoren Thanks 40.png",
    "PyConDE PyData 2025 Sponsoren Thanks 41.png",
    "PyConDE PyData 2025 Sponsoren Thanks 42.png",
    "PyConDE PyData 2025 Sponsoren Thanks 43.png",
    "PyConDE PyData 2025 Sponsoren Thanks 44.png",
    "PyConDE PyData 2025 Sponsoren Thanks 45.png",
    "PyConDE PyData 2025 Sponsoren Thanks 46.png",
    "PyConDE PyData 2025 Sponsoren Thanks 47.png",
    "PyConDE PyData 2025 Sponsoren Thanks 48.png",
    "PyConDE PyData 2025 Sponsoren Thanks 49.png",
    "PyConDE PyData 2025 Sponsoren Thanks 50.png",
]
names = [
    "Merck",
    "Pydantic Logfire",
    "QuantCo",
    "E.On",
    "Zeiss",
    "Hopsworks",
    "Rosenxt",
    "Gurobi Optimization",
    "JetBrains",
    "MOSTLY AI",
    "Blue Yonder",
    "Redis",
    "Okta",
    "Rosen",
    "Sovanta",
    "ExperTeach",
    "Kraken",
    "prokube",
    "Heidelberger Druckmaschinen AG",
    "inovex GmbH",
    "Lidl Stiftung & Co. KG",
    "Bausparkasse Schwäbisch Hall AG",
    "REWE Group",
    "Quansight",
    "items GmbH & Co. KG",
    "energy & meteo systems",
    "Cologne Intelligence",
    "&effect data solutions GmbH",
    "Innoflair",
    "quattro research GmbH",
    "Python Softwareverband e.V.",
    "NumFOCUS",
    "Pioneers Hub",
    "Python Software Foundation",
    "EuroPython Society (EPS)",
    "appliedAI Institute for Europe gGmbH",
    "Hessian AI",
    "ULB - University and State Library Darmstadt",
    "PyLadies Südwest",
    "PyLadies Hamburg",
    "PyLadies Berlin",
    "PyLadies Munich",
    "PyData Südwest",
    "PyData Rhein-Main",
    "PyData Berlin",
    "DjangoGirls",
    "AISR",
    "Probably Private",
    "spaCy",
    "Women in AI",
]

for fyle, name in zip(files, names, strict=False):
    fp = root / fyle
    fp.rename(root / f"{name}{fp.suffix}")
