name: Upload staging website

on:
  push:
    branches: ["development"]
  pull_request_target:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setting up python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Build static page
        run: make build

      - name: Upload to s3
        uses: jakejarvis/s3-sync-action@master
        env:
          SOURCE_DIR: tmp
          AWS_S3_BUCKET: 'pyconde-pydata-2025-staging'
          AWS_REGION: 'eu-central-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Post Staging URL as PR Comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo;
            const stagingUrl = "http://pyconde-pydata-2025-staging.s3-website.eu-central-1.amazonaws.com/";

            github.rest.issues.createComment({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: prNumber,
              body: `🚀 The staging site is live! [View here](${stagingUrl})`
            });
